#Fundamentals of TensorFlow

In [2]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [3]:
scalar=tf.constant(7)
scalar.ndim #Checking number of Dimensions ndim

0

In [4]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
vector=tf.constant([10.,10.],dtype=tf.float16)
vector

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([10., 10.], dtype=float16)>

### Creating Tensors using tf.Variable

In [6]:
changeable_tensor=tf.Variable([10,7]) #Variable Tensor
unchangeable_tensor=tf.constant([10,7]) # Constant Tensor
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [7]:
#Changing can't be done in normal way in tf.Variable, ex changeable_tensor[0]=7
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating Random Tensors

In [8]:
random_1=tf.random.Generator.from_seed(42) #SEED: If you pass the same number to two instances of the same operator, they will produce the same sequence of results.
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)# Basically, seed is like a flavour. Same seed for same operator= same results
random_2=random_2.normal(shape=(3,2))
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [9]:
#Shuffle a tensor, Useful to shuffle train cases and remove inherent bias in the data
#If we want our shuffled tensors to be in the same order, we have to use both global and operation seeds
tf.random.shuffle(random_1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [-0.23193763, -1.8107855 ],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

**Turn NumPy arrays into TensorFlow Tensors**
The main difference between them is that tensors can be run on a GPU(much faster)

In [10]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [11]:
A=tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [12]:
#Getting more info from Tensors
B=tf.random.Generator.from_seed(4)
B=B.normal(shape=(2,3,4,5,6))
print("Shape of Tensor:",B.shape)
print('Size of B:',tf.size(B))
print('Number of dimensions(Rank):',B.ndim)
print('Datatype of B:', B.dtype)

Shape of Tensor: (2, 3, 4, 5, 6)
Size of B: tf.Tensor(720, shape=(), dtype=int32)
Number of dimensions(Rank): 5
Datatype of B: <dtype: 'float32'>


In [13]:
B=tf.constant([10.7,11.2])
B.dtype

tf.float32

In [14]:
#Changing dtype in Tensorflow
C=tf.cast(B,dtype=tf.float16)
C,C.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([10.7, 11.2], dtype=float16)>,
 tf.float16)

**Aggregating Tensors**
Condesing tensors from multiple values dwon to smaller ampunt of values

In [15]:
A=tf.constant([-10,-7])
tf.abs(A) 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [17]:
#Lets take a random tensor
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([36, 75, 18, 13, 72, 46, 61, 99, 82, 60, 26, 74, 95, 63, 84, 91, 91,
       29, 29, 48, 28, 95, 33,  4, 51,  1, 80, 19, 26, 78, 41, 35, 85, 73,
       62, 56,  1, 48,  5, 97, 55, 21, 15, 18, 24, 80, 54, 84, 46, 69])>

In [18]:
mi=tf.reduce_min(E) #Finds min of tensor
ma=tf.reduce_max(E)
mean=tf.reduce_mean(E)
sum=tf.reduce_sum(E)
mi,ma,mean,sum

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=51>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2576>)

In [32]:
STD=tf.math.reduce_std(tf.cast(E,dtype=tf.float32)) #For std, we need our tensors as float32 or float64
Variance=STD**2
Variance,STD

(<tf.Tensor: shape=(), dtype=float32, numpy=833.00964>,
 <tf.Tensor: shape=(), dtype=float32, numpy=28.861906>)

**Finding positional maximum and minimum** Finding index at which the max or min value occurs in a row or column

In [34]:
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [36]:
#FInd the positional max
tf.argmax(F),F[tf.argmax(F)],tf.reduce_max(F)    #tf.math.argmax(input, axis=None, output_type=tf.dtypes.int64, name=None)
#Similarly tf.argmin()

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

**Squeezing Tensors** removing all single dimensions

In [38]:
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [39]:
G_squeezed=tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

**One Hot Encoding**

In [46]:
#Create some list of indices
ran_list=tf.range(4)
tf.one_hot(ran_list,depth=len(ran_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

**Tensors and NumPy**
changing numpy arrays to tensors give 64 bit type,
changing normal lists to tensors give 32 bit type

In [47]:
J=tf.constant(np.arange(10))
J

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [49]:
np.array(J),type(np.array(J)),J.numpy(),type(J.numpy())

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 numpy.ndarray,
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 numpy.ndarray)

In [50]:
#The default types of each are slightly different
numpy_J=tf.constant(np.arange(10)) # changing numpy arrays to tensors give 64 bit type
tensor_J=tf.constant(range(10))  #Changing normal lists to tensors gives 32 bit types
numpy_J.dtype,tensor_J.dtype

(tf.int64, tf.int32)

**Finding access to GPUs**

In [1]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
!nvidia-smi #command for checking GPU specs

Sat Aug 14 10:03:04 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   32C    P8    28W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note:** If you have access to a CUDA_enabled GPU, tensorflow will automatically use it whenever possible